export JAVA_OPTS="$JAVA_OPTS -DJDBC_CONNECTION_STRING=jdbc:mysql://localhost:3306/TestDB -DJDBC_USER_NAME=root -DJDBC_PASSWORD=root123"
export JAVA_OPTS="$JAVA_OPTS -DSESSION_CACHE_HOST=localhost -DSESSION_CACHE_PORT=6379"
